#!/usr/bin/env python3
"""
Generate the theme-clustering fixture inputs from a local QDR download.

The QDR deposit is not vendored into this repo — its data files are governed by
QDR's Standard Download Agreement, which is a gated term, not an open one. You
download it yourself; this script reads your local copy and writes the two input
files the fixture uses. Both generated files are gitignored.

    Acolin, Jessica; Jampel, Sonya. 2026. "Integrating End-User Needs and
    Perspectives in the Measurement of Young Adult Climate Change Distress."
    Qualitative Data Repository. https://doi.org/10.5064/F6PN4ARY. V1.

Usage:
    python3 prepare.py /path/to/the/QDR/folder
    python3 prepare.py            # tries the default Downloads location

Standard library only — no openpyxl needed.
"""

import re
import sys
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}

CODEBOOK = "Acolin-Jampel_Codebook.xlsx"
QUOTES = "Acolin-Jampel_ExcerptedQuotes.xlsx"

DEFAULT_DIR = (
    Path.home()
    / "Downloads"
    / "Integrating end user needs in the measurement of climate change distress (QDR)"
)


def read_sheet(xlsx_path):
    """Return the first worksheet as a list of {column_letter: value} dicts."""
    with zipfile.ZipFile(xlsx_path) as z:
        shared = []
        if "xl/sharedStrings.xml" in z.namelist():
            root = ET.fromstring(z.read("xl/sharedStrings.xml"))
            for si in root.findall("m:si", NS):
                shared.append(
                    "".join(e.text or "" for e in si.iter() if e.tag.endswith("}t"))
                )
        # The deposit's workbooks each have exactly one sheet.
        sheet_name = sorted(n for n in z.namelist() if n.startswith("xl/worksheets/"))[0]
        root = ET.fromstring(z.read(sheet_name))

        rows = []
        for row in root.find("m:sheetData", NS):
            cells = {}
            for c in row.findall("m:c", NS):
                col = "".join(ch for ch in c.get("r") if ch.isalpha())
                v = c.find("m:v", NS)
                inline = c.find("m:is", NS)
                if c.get("t") == "s" and v is not None:
                    val = shared[int(v.text)]
                elif inline is not None:
                    val = "".join(
                        e.text or "" for e in inline.iter() if e.tag.endswith("}t")
                    )
                else:
                    val = v.text if v is not None else ""
                cells[col] = (val or "").strip()
            rows.append(cells)
    return rows


def build_codes(rows):
    """Group codes under their research-question headings.

    Column A is the code, B the definition, C inductive/deductive.

    Columns D and E are deliberately dropped. D is a per-code colour and E a
    date. Neither is needed to cluster, and a colour column is exactly the kind
    of field that can encode the study team's own grouping — leaking the answer
    into the input. If you are ever unsure whether a column carries the answer,
    drop it; a fixture that leaks is worse than no fixture, because it produces
    a confident score that means nothing.
    """
    groups, current = [], None
    for cells in rows:
        a = cells.get("A", "")
        if not a or a == "Code":
            continue
        if a.lower().startswith("research question"):
            current = {"rq": re.sub(r"^Research question:\s*", "", a), "codes": []}
            groups.append(current)
            continue
        if current is None:
            current = {"rq": "(no research question stated)", "codes": []}
            groups.append(current)
        current["codes"].append(
            {
                "code": a,
                "definition": cells.get("B", ""),
                "origin": cells.get("C", ""),
            }
        )
    return groups


def write_codes(groups, out_path):
    n = sum(len(g["codes"]) for g in groups)
    lines = [
        "# Input — codes and research questions",
        "",
        "Generated by `prepare.py`. Do not edit; do not commit.",
        "",
        "This is the **only** thing the model under test may see for the",
        "clustering run. The theme set is held out in `answer-key.md` — do not",
        "open it, paste it, or summarise it into the session.",
        "",
        f"{n} codes across {len(groups)} research questions.",
        "",
        "Source: Acolin & Jampel 2026, QDR, https://doi.org/10.5064/F6PN4ARY",
        "",
        "---",
        "",
    ]
    for i, g in enumerate(groups, 1):
        lines += [f"## Research question {i}", "", g["rq"], "", "| Code | Definition | Origin |", "|---|---|---|"]
        for c in g["codes"]:
            code = c["code"].replace("|", "\\|")
            defn = (c["definition"] or "—").replace("|", "\\|").replace("\n", " ")
            origin = (c["origin"] or "—").replace("|", "\\|")
            lines.append(f"| {code} | {defn} | {origin} |")
        lines.append("")
    out_path.write_text("\n".join(lines))
    return n


def write_quotes(rows, out_path):
    data = [r for r in rows[1:] if r.get("A")]
    lines = [
        "# Input — coded quotations",
        "",
        "Generated by `prepare.py`. Do not edit; do not commit.",
        "",
        "Each row is a code and the quotations the study team chose to",
        "illustrate it. **These are exemplars selected after coding, not a",
        "corpus.** They carry no participant IDs, no speaker labels, and no",
        "focus-group attribution, and they cover only a subset of the codebook.",
        "",
        "Used by tests 2 and 3 in `README.md`. Not used by test 1 — showing",
        "these during clustering would supply evidence the model is supposed to",
        "be reasoning about without.",
        "",
        "Source: Acolin & Jampel 2026, QDR, https://doi.org/10.5064/F6PN4ARY",
        "",
        "---",
        "",
    ]
    for i, r in enumerate(data, 1):
        lines += [f"## Q{i}. {r.get('A','')}", "", r.get("B", "").strip(), ""]
    out_path.write_text("\n".join(lines))
    return len(data)


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DIR
    here = Path(__file__).parent

    if not src.is_dir():
        sys.exit(
            f"Not a directory: {src}\n\n"
            "Download the deposit from https://doi.org/10.5064/F6PN4ARY "
            "(free QDR account required) and pass its folder as the first "
            "argument."
        )

    missing = [f for f in (CODEBOOK, QUOTES) if not (src / f).is_file()]
    if missing:
        sys.exit(
            f"Missing from {src}:\n  " + "\n  ".join(missing) + "\n\n"
            "Note that QDR's README lists ExcerptedQuotes.xlsx among the "
            "included files while MANIFEST.TXT omits it, and at least one "
            "download has arrived without it. Re-download if it is absent."
        )

    groups = build_codes(read_sheet(src / CODEBOOK))
    n_codes = write_codes(groups, here / "input-codes.md")
    n_rows = write_quotes(read_sheet(src / QUOTES), here / "input-quotes.md")

    print(f"input-codes.md   {n_codes} codes across {len(groups)} research questions")
    print(f"input-quotes.md  {n_rows} coded rows")
    print("\nBoth files are gitignored. Read README.md before running the tests.")
    print("Do not open answer-key.md until the run is finished.")


if __name__ == "__main__":
    main()
