#!/usr/bin/env python3
"""
Research PDF Generator (USWDS styling: U.S. Web Design System color tokens,
Public Sans typeface)
Permanent script -- not regenerated by LLM each time.
Usage: python3 generate_pdf.py <markdown_file> <output_pdf>
       [--cover] [--title TITLE] [--subtitle SUBTITLE] [--description DESC]
       [--date DATE] [--team TEAM] [--footer-note NOTE] [--font-dir FONT_DIR]
"""

import os, re, sys, argparse
from functools import partial
from datetime import datetime
from types import SimpleNamespace

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether
)
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus.flowables import Flowable

# ============================================================
# 1. FONTS
# ============================================================
# Public Sans ships with the skill in <skill>/assets/fonts/ (SIL Open Font
# License 1.1; OFL.txt and LICENSE.md sit beside the TTFs). Nothing is
# downloaded. Registration is deferred until build_document() runs so that
# `--help` and argparse errors never touch the TTF files.
#
# Every font name the renderer uses goes through font(face). After
# register_fonts() it returns "PublicSans-<face>" when all ten faces loaded,
# or the matching Helvetica face when any of them failed.

DEFAULT_FONT_DIR = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "assets", "fonts"
))

FONT_FACES = ["Light", "Regular", "Medium", "SemiBold", "Bold",
              "Italic", "LightItalic", "MediumItalic", "SemiBoldItalic", "BoldItalic"]

# Built-in stand-in for each face when Public Sans can't be loaded.
HELVETICA_FALLBACK = {
    "Light":          "Helvetica",
    "Regular":        "Helvetica",
    "Medium":         "Helvetica-Bold",
    "SemiBold":       "Helvetica-Bold",
    "Bold":           "Helvetica-Bold",
    "Italic":         "Helvetica-Oblique",
    "LightItalic":    "Helvetica-Oblique",
    "MediumItalic":   "Helvetica-BoldOblique",
    "SemiBoldItalic": "Helvetica-BoldOblique",
    "BoldItalic":     "Helvetica-BoldOblique",
}

# Inline <b>, <i>, <b><i> mapping for each base face a style uses:
# base -> (normal, bold, italic, boldItalic). Bold is always Bold (700);
# italic keeps the base weight. The Italic base face (callouts) resolves
# through the Regular family, whose italic member it is. The Helvetica
# fallback needs no registration: ReportLab maps that family built in.
FONT_FAMILIES = {
    "Light":    ("Light",    "Bold", "LightItalic",    "BoldItalic"),
    "Regular":  ("Regular",  "Bold", "Italic",         "BoldItalic"),
    "Medium":   ("Medium",   "Bold", "MediumItalic",   "BoldItalic"),
    "SemiBold": ("SemiBold", "Bold", "SemiBoldItalic", "BoldItalic"),
}

# Face -> registered font name. Starts on Helvetica so nothing can reference
# an unregistered name; register_fonts() switches it to Public Sans.
_active_faces = dict(HELVETICA_FALLBACK)


def font(face):
    """The font name to use for a Public Sans face ("Light", "SemiBold", ...):
    "PublicSans-<face>" when Public Sans is registered, else its Helvetica
    stand-in. The single place font names are decided."""
    return _active_faces[face]


def register_fonts(font_dir=None):
    """Register the ten Public Sans faces from font_dir (default: the fonts
    bundled in <skill>/assets/fonts/) plus the inline bold/italic mapping for
    every base face. All-or-nothing: if any face fails, font() resolves every
    face to Helvetica and one warning goes to stderr. Returns True when
    Public Sans is active."""
    global _active_faces
    font_dir = os.path.expanduser(font_dir) if font_dir else DEFAULT_FONT_DIR

    missing = [f"PublicSans-{face}.ttf" for face in FONT_FACES
               if not os.path.isfile(os.path.join(font_dir, f"PublicSans-{face}.ttf"))]
    if len(missing) == len(FONT_FACES):
        problem = "no PublicSans-*.ttf files found"
    elif missing:
        problem = "missing " + ", ".join(missing)
    else:
        problem = None
        try:
            for face in FONT_FACES:
                pdfmetrics.registerFont(TTFont(
                    f"PublicSans-{face}",
                    os.path.join(font_dir, f"PublicSans-{face}.ttf"),
                ))
            # Families go after every registerFont call: registering a TTF
            # resets that face's own mapping.
            for base, (normal, bold, italic, bold_italic) in FONT_FAMILIES.items():
                pdfmetrics.registerFontFamily(
                    f"PublicSans-{base}",
                    normal=f"PublicSans-{normal}",
                    bold=f"PublicSans-{bold}",
                    italic=f"PublicSans-{italic}",
                    boldItalic=f"PublicSans-{bold_italic}",
                )
        except Exception as e:
            problem = str(e)

    if problem:
        _active_faces = dict(HELVETICA_FALLBACK)
        print(
            f"WARNING: Public Sans could not be loaded from {font_dir} ({problem}). "
            "Falling back to Helvetica: the PDF will render, but not in Public Sans.",
            file=sys.stderr,
        )
        return False

    _active_faces = {face: f"PublicSans-{face}" for face in FONT_FACES}
    return True

# ============================================================
# 2. COLORS -- U.S. Web Design System (USWDS) tokens
# ============================================================
# Published USWDS defaults: designsystem.digital.gov/design-tokens/color/
# Light-dominant pages with one accent (PRIMARY). PRIMARY_DARKER is the dark
# anchor (cover background) and ACCENT_COOL the accent on dark. Small text is
# INK or BASE_DARK, never a lighter gray.
PRIMARY_LIGHTER     = HexColor("#D9E8F6")  # accent tint fill: callout box
PRIMARY             = HexColor("#005EA2")  # the single accent: bars, TOC numbers, links
PRIMARY_DARK        = HexColor("#1A4480")  # secondary accent (unused by the current layout)
PRIMARY_DARKER      = HexColor("#162E51")  # dark anchor: cover background, callout text
ACCENT_COOL         = HexColor("#00BDE3")  # accent on dark: cover rule, subtitle, labels
ACCENT_COOL_LIGHTER = HexColor("#E1F3F8")  # light text on dark: cover description
INK                 = HexColor("#1B1B1B")  # body and heading text
BASE_DARK           = HexColor("#565C65")  # secondary text: footers, attributions
BASE_LIGHTER        = HexColor("#DFE1E2")  # rules and dividers (non-text)
BASE_LIGHTEST       = HexColor("#F0F0F0")  # fills: table header, zebra rows
WHITE               = HexColor("#FFFFFF")

# USWDS state tokens: signal indicators only, never decoration (the current
# layout uses none). Text uses the darker variant; WARNING is a fill only,
# always with INK text on it.
SUCCESS             = HexColor("#00A91C")
SUCCESS_DARKER      = HexColor("#216E1F")
ERROR               = HexColor("#D54309")
ERROR_DARK          = HexColor("#B50909")
WARNING             = HexColor("#FFBE2E")
INFO                = HexColor("#00BDE3")
INFO_DARKER         = HexColor("#2E6276")

# ============================================================
# 3. PAGE LAYOUT
# ============================================================
PAGE_W, PAGE_H = letter
LEFT_MARGIN   = 0.75 * inch
RIGHT_MARGIN  = 0.75 * inch
TOP_MARGIN    = 0.75 * inch
BOTTOM_MARGIN = 0.85 * inch
CONTENT_W     = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ============================================================
# 4. PARAGRAPH STYLES
# ============================================================
# Filled by build_styles() after register_fonts(), so every fontName goes
# through font() and names a face that is actually registered.
STYLES = SimpleNamespace()


def build_styles():
    """Create every paragraph style. Call after register_fonts()."""
    S = STYLES
    S.section_title = ParagraphStyle(
        "SectionTitle", fontName=font("Light"), fontSize=32, leading=36,
        textColor=INK, spaceBefore=0, spaceAfter=6,
    )
    S.h2 = ParagraphStyle(
        "H2", fontName=font("Medium"), fontSize=16, leading=22,
        textColor=INK, spaceBefore=16, spaceAfter=6,
    )
    S.h3 = ParagraphStyle(
        "H3", fontName=font("Medium"), fontSize=12, leading=17,
        textColor=INK, spaceBefore=12, spaceAfter=5,
    )
    S.body = ParagraphStyle(
        "Body", fontName=font("Regular"), fontSize=9.5, leading=14.5,
        textColor=INK, spaceBefore=0, spaceAfter=6, alignment=TA_LEFT,
    )
    S.bullet = ParagraphStyle(
        "Bullet", fontName=font("Regular"), fontSize=9.5, leading=14.5,
        textColor=INK, spaceBefore=0, spaceAfter=3,
        leftIndent=18, bulletIndent=0,
        bulletFontName=font("Regular"), bulletFontSize=9.5,
    )
    S.sub_bullet = ParagraphStyle(
        "SubBullet", fontName=font("Regular"), fontSize=9.5, leading=14.5,
        textColor=INK, spaceBefore=0, spaceAfter=3,
        leftIndent=36, bulletIndent=18,
        bulletFontName=font("Regular"), bulletFontSize=9.5,
    )
    S.callout = ParagraphStyle(
        "Callout", fontName=font("Italic"), fontSize=9, leading=14,
        textColor=PRIMARY_DARKER, leftIndent=12, rightIndent=12, spaceBefore=4, spaceAfter=4,
    )
    S.callout_attribution = ParagraphStyle(
        "CalloutAttribution", fontName=font("Regular"), fontSize=8, leading=11,
        textColor=BASE_DARK, leftIndent=12, spaceBefore=0, spaceAfter=2,
    )
    S.table_header = ParagraphStyle(
        "TableHeader", fontName=font("SemiBold"), fontSize=8.5, leading=12,
        textColor=INK,
    )
    S.table_cell = ParagraphStyle(
        "TableCell", fontName=font("Regular"), fontSize=8.5, leading=12,
        textColor=INK,
    )
    S.toc_title = ParagraphStyle(
        "TOCTitle", fontName=font("Light"), fontSize=28, leading=32,
        textColor=INK, spaceAfter=16,
    )
    S.toc_num = ParagraphStyle(
        "TOCNum", fontName=font("Light"), fontSize=14, leading=24,
        textColor=PRIMARY,
    )
    S.toc_text = ParagraphStyle(
        "TOCText", fontName=font("Light"), fontSize=14, leading=24,
        textColor=INK,
    )
    S.cover_title = ParagraphStyle(
        "CoverTitle", fontName=font("Light"), fontSize=45, leading=50,
        textColor=WHITE, spaceAfter=27,
    )
    S.cover_subtitle = ParagraphStyle(
        "CoverSubtitle", fontName=font("Light"), fontSize=24, leading=26,
        textColor=ACCENT_COOL, spaceAfter=14,
    )
    S.cover_desc = ParagraphStyle(
        "CoverDesc", fontName=font("Light"), fontSize=14, leading=20,
        textColor=ACCENT_COOL_LIGHTER,
    )
    S.cover_meta_label = ParagraphStyle(
        "CoverMetaLabel", fontName=font("Light"), fontSize=12, leading=13,
        textColor=ACCENT_COOL, spaceAfter=2,
    )
    S.cover_meta_value = ParagraphStyle(
        "CoverMetaValue", fontName=font("Light"), fontSize=14, leading=15,
        textColor=WHITE, spaceAfter=39,
    )
    return S


# ============================================================
# 5. CUSTOM FLOWABLES
# ============================================================
class AccentBar(Flowable):
    def __init__(self, width=40, height=3):
        Flowable.__init__(self)
        self._bar_w = width
        self._bar_h = height
        self.width = width
        self.height = height + 4

    def draw(self):
        self.canv.setFillColor(PRIMARY)
        self.canv.rect(0, 2, self._bar_w, self._bar_h, fill=1, stroke=0)


class ThinRule(Flowable):
    def __init__(self, width=None, color=None, thickness=0.5):
        Flowable.__init__(self)
        self._rule_w = width or CONTENT_W
        self._color = color or BASE_LIGHTER
        self._thickness = thickness
        self.width = self._rule_w
        self.height = 4

    def draw(self):
        self.canv.setStrokeColor(self._color)
        self.canv.setLineWidth(self._thickness)
        self.canv.line(0, 2, self._rule_w, 2)


class CalloutBox(Flowable):
    def __init__(self, quote_text, attribution_text=None, width=None):
        Flowable.__init__(self)
        self.quote_text = quote_text
        self.attribution_text = attribution_text
        self._width = width or CONTENT_W
        self._calc_height()

    def _calc_height(self):
        inner_w = self._width - 24
        self._quote_para = Paragraph(self.quote_text, STYLES.callout)
        qw, qh = self._quote_para.wrap(inner_w, 1000)
        self._quote_h = qh
        self._attr_h = 0
        self._attr_para = None
        if self.attribution_text:
            self._attr_para = Paragraph(
                "\u2014 " + self.attribution_text, STYLES.callout_attribution
            )
            aw, ah = self._attr_para.wrap(inner_w, 1000)
            self._attr_h = ah
        self.height = 10 + self._quote_h + (4 if self._attr_para else 0) + self._attr_h + 10
        self.width = self._width

    def wrap(self, availWidth, availHeight):
        self._width = availWidth
        self._calc_height()
        return (self._width, self.height)

    def draw(self):
        canvas = self.canv
        canvas.setFillColor(PRIMARY_LIGHTER)
        canvas.roundRect(0, 0, self._width, self.height, 3, fill=1, stroke=0)
        canvas.setFillColor(PRIMARY)
        canvas.rect(0, 0, 3, self.height, fill=1, stroke=0)
        y = self.height - 10 - self._quote_h
        self._quote_para.drawOn(canvas, 12, y)
        if self._attr_para:
            y = y - 4 - self._attr_h
            self._attr_para.drawOn(canvas, 12, y)


# ============================================================
# 6. EMOJI STRIPPING
# ============================================================
def strip_emoji(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "\U0001f926-\U0001f937"
        "\U00010000-\U0010ffff"
        "\u200d"
        "\u2640-\u2642"
        "\ufe0f"
        "\u2600-\u26FF"
        "\u2700-\u27BF"
        "\u23E9-\u23F3"
        "\u23F8-\u23FA"
        "\u25AA-\u25FE"
        "\u200C-\u200D"
        "\u2934-\u2935"
        "\u3030\u303D"
        "\uFE00-\uFE0F"
        "]+",
        flags=re.UNICODE,
    )
    return emoji_pattern.sub("", text)


# ============================================================
# 7. MARKDOWN PARSER
# ============================================================
def escape_xml(text):
    """Escape XML special chars for ReportLab Paragraph."""
    text = text.replace("&", "&amp;")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    return text


def format_inline(text):
    """Convert markdown inline formatting to ReportLab XML tags.

    The raw input is XML-escaped FIRST so any literal `&`, `<`, or `>` in
    body content survives without crashing ReportLab's mini-XML parser.
    Markdown tokens are then converted to tags we generate ourselves --
    those tags are not double-escaped because we control them."""
    text = escape_xml(text)
    # Bold + italic
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'<b><i>\1</i></b>', text)
    # Bold
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
    # Italic
    text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
    # Links -- only external URLs, skip internal anchors. The URL pattern
    # tolerates a single matched-paren pair (e.g. Wikipedia disambiguation
    # links: https://en.wikipedia.org/wiki/Foo_(disambiguation)).
    def _link_replace(m):
        label, url = m.group(1), m.group(2)
        if url.startswith("http://") or url.startswith("https://"):
            return f'<a href="{url}" color="#{PRIMARY.hexval()[2:]}">{label}</a>'
        return f'<b>{label}</b>'  # internal link: just bold the text
    text = re.sub(
        r'\[([^\]]+)\]\(([^\s()]+(?:\([^\s()]*\)[^\s()]*)*)\)',
        _link_replace,
        text,
    )
    return text


def _heading_text(line):
    """Return (level, text) if line is a markdown heading, else (0, '')."""
    m = re.match(r'^(#{1,6})\s+(.*)$', line.strip())
    if not m:
        return 0, ''
    return len(m.group(1)), m.group(2).strip()


def _strip_block_by_heading(md_text, heading_names):
    """Strip a heading whose text matches one of heading_names (case-insensitive),
    and everything beneath it up to the next heading. Also consume a single
    trailing '---' rule on the line directly after the block, so we don't
    leave an orphan ThinRule. Returns (block_lines_without_heading, cleaned_md_text).
    If no matching heading found, returns ([], md_text)."""
    lines = md_text.split("\n")
    targets = {h.lower() for h in heading_names}
    start = -1
    for i, line in enumerate(lines):
        level, text = _heading_text(line)
        if level and text.lower() in targets:
            start = i
            break
    if start == -1:
        return [], md_text

    # Find end: next heading line, exclusive
    end = len(lines)
    for j in range(start + 1, len(lines)):
        level, _ = _heading_text(lines[j])
        if level:
            end = j
            break

    block_lines = lines[start + 1:end]

    # Consume a trailing '---' rule (and any blank line right before it) that
    # was acting as a section terminator after this block.
    trim_end = end
    if trim_end < len(lines) and lines[trim_end].strip() in ("---", "***", "___"):
        trim_end += 1

    cleaned = "\n".join(lines[:start] + lines[trim_end:])
    return block_lines, cleaned


def extract_and_strip_toc(md_text):
    """Find a 'Contents' or 'Table of Contents' heading and parse the numbered
    list beneath it. Returns (toc_titles, md_text_without_toc_block)."""
    block_lines, cleaned = _strip_block_by_heading(
        md_text, ["contents", "table of contents"]
    )
    if not block_lines:
        return [], md_text

    titles = []
    for line in block_lines:
        m = re.match(r'^\s*\d+\.\s+(.+?)\s*$', line)
        if m:
            # Strip any markdown formatting markers from the title
            t = m.group(1).strip()
            t = re.sub(r'\*\*(.+?)\*\*', r'\1', t)
            t = re.sub(r'\*(.+?)\*', r'\1', t)
            titles.append(t)
    return titles, cleaned


def strip_cover_block(md_text):
    """Remove a '## Cover' block (heading + body + trailing rule) entirely."""
    _, cleaned = _strip_block_by_heading(md_text, ["cover"])
    return cleaned


def strip_h1_if_matches_cover(md_text, cover_title):
    """If the first H1 in the document matches cover_title (case-insensitive,
    trimmed), drop that line and a single immediately-following '---' rule.
    Avoids the cover title appearing twice when a cover page is rendered."""
    if not cover_title:
        return md_text
    lines = md_text.split("\n")
    target = cover_title.strip().lower()
    for i, line in enumerate(lines):
        level, text = _heading_text(line)
        if not level:
            continue
        if level == 1 and text.lower() == target:
            # Drop the H1 line. Also drop a single trailing '---' rule that
            # often follows a top-of-document title.
            drop_to = i + 1
            # Skip a single blank line if present before the rule
            j = drop_to
            while j < len(lines) and lines[j].strip() == "":
                j += 1
            if j < len(lines) and lines[j].strip() in ("---", "***", "___"):
                drop_to = j + 1
            return "\n".join(lines[:i] + lines[drop_to:])
        # Any other heading found before the title H1 means there's no
        # leading-title to strip; bail out.
        break
    return md_text


def suppress_leading_rule(story):
    """If the first non-Spacer flowable in the body story is a ThinRule, drop
    it. Stops a stray gray line from opening the body."""
    for i, item in enumerate(story):
        if isinstance(item, Spacer):
            continue
        if isinstance(item, ThinRule):
            del story[i]
        return story
    return story


def parse_table(lines):
    """Parse markdown table lines into ReportLab Table."""
    rows = []
    for i, line in enumerate(lines):
        line = line.strip().strip("|")
        if i == 1 and re.match(r'^[\s\-|:]+$', line):
            continue  # skip separator
        cells = [c.strip() for c in line.split("|")]
        rows.append(cells)

    if not rows:
        return None

    # Build table data with Paragraphs
    table_data = []
    for i, row in enumerate(rows):
        style = STYLES.table_header if i == 0 else STYLES.table_cell
        table_data.append([Paragraph(format_inline(c), style) for c in row])

    # Calculate column widths
    n_cols = len(table_data[0])
    col_w = CONTENT_W / n_cols

    t = Table(table_data, colWidths=[col_w] * n_cols, repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND',      (0, 0), (-1, 0), BASE_LIGHTEST),
        ('TEXTCOLOR',       (0, 0), (-1, 0), INK),
        ('FONTNAME',        (0, 0), (-1, 0), font("SemiBold")),
        ('FONTNAME',        (0, 1), (-1, -1), font("Regular")),
        ('FONTSIZE',        (0, 0), (-1, -1), 8.5),
        ('TOPPADDING',      (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING',   (0, 0), (-1, -1), 5),
        ('LEFTPADDING',     (0, 0), (-1, -1), 6),
        ('RIGHTPADDING',    (0, 0), (-1, -1), 6),
        ('LINEBELOW',       (0, 0), (-1, 0), 1, INK),
        ('LINEBELOW',       (0, 1), (-1, -1), 0.4, BASE_LIGHTER),
        ('VALIGN',          (0, 0), (-1, -1), 'TOP'),
        ('ROWBACKGROUNDS',  (0, 1), (-1, -1), [WHITE, BASE_LIGHTEST]),
    ]))
    return t


def parse_markdown(md_text, doc_title):
    """Parse markdown into ReportLab story (list of flowables).

    Returns just the story list. Body is rendered as continuous flow with
    inline headings; page breaks come from <!-- pagebreak --> only. Cover
    title and TOC are handled by separate preprocessing helpers."""
    lines = md_text.split("\n")
    story = []
    i = 0
    in_table = False
    table_lines = []

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Page break marker (case-insensitive). Must be checked before the
        # generic comment skip, otherwise it would be silently swallowed.
        if re.match(r'^<!--\s*page\s*break\s*-->\s*$', stripped, re.IGNORECASE):
            story.append(PageBreak())
            i += 1
            continue

        # Skip HTML comments
        if stripped.startswith("<!--"):
            comment_start = i
            # Safety limit: max 50 lines for a comment block
            while i < len(lines) and i - comment_start < 50 and "-->" not in lines[i]:
                i += 1
            # Skip the closing line if found
            if i < len(lines) and "-->" in lines[i]:
                i += 1
            continue

        # Table detection
        if stripped.startswith("|") and not in_table:
            in_table = True
            table_lines = [stripped]
            i += 1
            continue
        elif in_table:
            if stripped.startswith("|"):
                table_lines.append(stripped)
                i += 1
                continue
            else:
                # End of table
                t = parse_table(table_lines)
                if t:
                    story.append(t)
                    story.append(Spacer(1, 8))
                in_table = False
                table_lines = []
                # Don't increment i, re-process this line
                continue

        # Horizontal rule
        if stripped in ("---", "***", "___"):
            # Skip the very first line (treat a leading rule as YAML
            # frontmatter delimiter rather than a body rule).
            if i > 0:
                story.append(ThinRule())
                story.append(Spacer(1, 6))
            i += 1
            continue

        # H1 -- inline only. No PageBreak, no AccentBar treatment. The cover
        # page (if rendered) handles the document title; preprocessing strips
        # a leading H1 that matches the cover title.
        if stripped.startswith("# ") and not stripped.startswith("## "):
            title = stripped[2:].strip()
            story.append(Paragraph(format_inline(title), STYLES.section_title))
            i += 1
            continue

        # H2 -- inline only. Render verbatim so authored numbering ("1. Foo")
        # is preserved in the body. The TOC display strips numbering separately.
        if stripped.startswith("## "):
            title = stripped[3:].strip()
            story.append(Paragraph(format_inline(title), STYLES.h2))
            i += 1
            continue

        # H3
        if stripped.startswith("### ") and not stripped.startswith("#### "):
            title = stripped[4:].strip()
            story.append(Paragraph(format_inline(title), STYLES.h3))
            i += 1
            continue

        # H4/H5/H6 — render at H3 size (smallest heading style we have)
        if stripped.startswith("#### "):
            title = stripped.lstrip("#").strip()
            story.append(Paragraph(format_inline(title), STYLES.h3))
            i += 1
            continue

        # Blockquote -> CalloutBox
        if stripped.startswith("> "):
            quote_lines = []
            quote_start = i
            # Safety limit: max 20 lines per quote
            while i < len(lines) and i - quote_start < 20 and lines[i].strip().startswith("> "):
                q = lines[i].strip()[2:].strip()
                # Strip a single italic marker wrapping the quote (*"..."*).
                # A leading or trailing ** belongs to bold markup; keep it.
                q = re.sub(r'^\*(?!\*)"?|"?(?<!\*)\*$', '', q)
                q = q.strip('"').strip()
                quote_lines.append(q)
                i += 1

            quote_text = " ".join(quote_lines)
            
            # Limit quote length to prevent ReportLab issues
            if len(quote_text) > 1000:
                quote_text = quote_text[:1000] + "..."

            # Check for attribution on next line
            attribution = None
            if i < len(lines):
                next_line = lines[i].strip()
                # Match patterns like "-- Name, ID" or "> -- Name"
                attr_match = re.match(r'^(?:>?\s*)?(?:\u2014|--|---)\s*(.+)$', next_line)
                if attr_match:
                    attribution = attr_match.group(1).strip()
                    i += 1

            try:
                story.append(Spacer(1, 8))
                story.append(KeepTogether([
                    CalloutBox(
                        format_inline(quote_text),
                        format_inline(attribution) if attribution else None,
                    )
                ]))
                story.append(Spacer(1, 8))
            except Exception as e:
                print(f"WARNING: Failed to create quote at line {quote_start}: {e}", file=sys.stderr)
                # Skip this quote and continue
                pass
            continue

        # Sub-bullet (indented)
        if re.match(r'^  +[-*]\s', line):
            text = re.sub(r'^\s+[-*]\s+', '', line).strip()
            story.append(Paragraph(
                f'<bullet>\u2022</bullet>{format_inline(text)}',
                STYLES.sub_bullet
            ))
            i += 1
            continue

        # Bullet
        if stripped.startswith("- ") or stripped.startswith("* "):
            text = stripped[2:].strip()
            story.append(Paragraph(
                f'<bullet>\u2014</bullet>{format_inline(text)}',
                STYLES.bullet
            ))
            i += 1
            continue

        # Empty line
        if not stripped:
            i += 1
            continue

        # Body text
        # Collect consecutive non-empty, non-special lines
        para_lines = []
        start_i = i
        while i < len(lines):
            # Safety check: prevent infinite loops
            if i - start_i > 100:
                print(f"WARNING: Breaking paragraph collection at line {i} (too many lines)", file=sys.stderr)
                break
            
            l = lines[i].strip()
            if not l or l.startswith("#") or l.startswith("|") or l.startswith(">") or l.startswith("- ") or l.startswith("* ") or l.startswith("<!--") or re.match(r'^  +[-*]\s', lines[i]):
                break
            para_lines.append(l)
            i += 1

        if para_lines:
            text = " ".join(para_lines)
            # Limit text length to prevent ReportLab hangs
            if len(text) > 3000:
                text = text[:3000] + "..."
            try:
                story.append(Paragraph(format_inline(text), STYLES.body))
            except Exception as e:
                print(f"WARNING: Failed to create paragraph at line {start_i}: {e}", file=sys.stderr)
                # Skip this paragraph and continue
                pass
        else:
            # Current line is unrecognized (matched an inner-loop break condition
            # that the outer loop doesn't explicitly handle — e.g. a bare ">",
            # a "#foo" with no space, or a heading level we don't render).
            # Advance unconditionally so we never spin on the same line.
            print(f"WARNING: Skipping unrecognized line {i}: {lines[i][:80]!r}", file=sys.stderr)
            i += 1

    # Flush remaining table
    if in_table and table_lines:
        t = parse_table(table_lines)
        if t:
            story.append(t)

    return story


# ============================================================
# 8. PAGE CALLBACKS
# ============================================================
# Optional cover logo. No logo ships with the skill: a team that wants its
# own mark on the cover drops an SVG at <skill>/assets/logo.svg (the script
# lives in <skill>/scripts/). If the file is absent, the cover renders
# without a logo.
LOGO_PATH = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "assets", "logo.svg"
))


def cover_page_cb(canvas, doc):
    canvas.saveState()
    # Background fill
    canvas.setFillColor(PRIMARY_DARKER)
    canvas.rect(0, 0, PAGE_W, PAGE_H, fill=1, stroke=0)
    # Accent line
    canvas.setStrokeColor(ACCENT_COOL)
    canvas.setLineWidth(1)
    accent_y = PAGE_H - 122
    canvas.line(LEFT_MARGIN, accent_y, LEFT_MARGIN + CONTENT_W, accent_y)
    # Logo (bottom-right)
    if os.path.exists(LOGO_PATH):
        from reportlab.graphics import renderPDF
        try:
            from svglib.svglib import svg2rlg
            drawing = svg2rlg(LOGO_PATH)
            if drawing:
                scale_w = 45 / drawing.width
                scale_h = 100 / drawing.height
                scale = min(scale_w, scale_h)
                drawing.width *= scale
                drawing.height *= scale
                drawing.scale(scale, scale)
                logo_x = PAGE_W - 57 - drawing.width
                logo_y = 57
                renderPDF.draw(drawing, canvas, logo_x, logo_y)
        except ImportError:
            pass  # svglib not installed, skip logo
        except Exception as e:
            # A team-supplied SVG svglib can't parse must not sink the build.
            print(f"WARNING: Could not draw cover logo {LOGO_PATH}: {e}", file=sys.stderr)
    canvas.restoreState()


def content_page_cb(canvas, doc, document_title="", report_date="", footer_note=None):
    """Footer-only page decoration. Document title, report date, and the
    optional footer note are bound by the caller via functools.partial so
    we don't lean on globals."""
    canvas.saveState()
    # Footer only -- no top header. Page number lives on the footer right.
    canvas.setStrokeColor(BASE_LIGHTER)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_MARGIN, BOTTOM_MARGIN - 0.15 * inch, PAGE_W - RIGHT_MARGIN, BOTTOM_MARGIN - 0.15 * inch)
    canvas.setFont(font("Regular"), 6.5)
    canvas.setFillColor(BASE_DARK)
    footer_left = f"{document_title}  |  {report_date}"
    if footer_note:
        footer_right = f"{footer_note}  ·  Page {doc.page}"
    else:
        footer_right = f"Page {doc.page}"
    canvas.drawString(LEFT_MARGIN, BOTTOM_MARGIN - 0.35 * inch, footer_left)
    canvas.drawRightString(PAGE_W - RIGHT_MARGIN, BOTTOM_MARGIN - 0.35 * inch, footer_right)
    canvas.restoreState()


# ============================================================
# 9. BUILD DOCUMENT
# ============================================================
def build_cover(title, subtitle=None, description=None, study_date=None, team=None):
    """Build cover page story elements. Only title is required.

    All caller-supplied strings are XML-escaped before going to ReportLab
    so a literal `&` in a CLI argument (e.g. --team "AI & Research")
    doesn't crash the build."""
    story = []
    story.append(Spacer(1, 1.7 * inch))
    story.append(Paragraph(escape_xml(title), STYLES.cover_title))
    if subtitle:
        story.append(Paragraph(escape_xml(subtitle), STYLES.cover_subtitle))
    if description:
        story.append(Paragraph(escape_xml(description), STYLES.cover_desc))

    # Only add metadata section if there's metadata to show
    has_metadata = study_date or team
    if has_metadata:
        # Push metadata toward bottom
        story.append(Spacer(1, 2.5 * inch))
        if study_date:
            story.append(Paragraph("Research date", STYLES.cover_meta_label))
            story.append(Paragraph(escape_xml(study_date), STYLES.cover_meta_value))
        if team:
            story.append(Paragraph("Team", STYLES.cover_meta_label))
            story.append(Paragraph(escape_xml(team), STYLES.cover_meta_value))

    story.append(PageBreak())
    return story


def build_toc(toc_titles):
    """Build the accent-numbered table of contents page from a list of
    titles. Returns [] when toc_titles is empty (caller decides whether the
    Contents block was found in the markdown)."""
    if not toc_titles:
        return []

    story = []
    story.append(Spacer(1, 0.3 * inch))
    story.append(AccentBar(40, 3))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Contents", STYLES.toc_title))
    story.append(ThinRule(color=INK, thickness=0.75))
    story.append(Spacer(1, 12))

    for idx, title in enumerate(toc_titles, 1):
        # Strip authored leading numbering ("1. Foo") for the display only —
        # the accent "01" badge replaces it.
        display = re.sub(r'^\s*\d+\.\s*', '', title).strip()
        num = f"{idx:02d}"
        row = [[Paragraph(num, STYLES.toc_num),
                Paragraph(escape_xml(display), STYLES.toc_text)]]
        t = Table(row, colWidths=[0.6 * inch, 5.5 * inch])
        t.setStyle(TableStyle([
            ('VALIGN',     (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME',   (0, 0), (-1, -1), font("Light")),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('LINEBELOW',  (0, 0), (-1, -1), 0.3, BASE_LIGHTER),
        ]))
        story.append(t)

    story.append(PageBreak())
    return story


def _default_title_from_path(md_path):
    base = os.path.splitext(os.path.basename(md_path))[0]
    return base.replace("-", " ").replace("_", " ").strip().title() or "Research Report"


def build_document(md_path, output_path, cover=False, title=None, subtitle=None,
                   description=None, study_date=None, team=None, font_dir=None,
                   footer_note=None):
    # Register fonts here (not at import time) so --help and argparse
    # errors never touch the TTF files, then build every style through
    # font() so the names match what was registered.
    register_fonts(font_dir)
    build_styles()

    with open(md_path, "r", encoding="utf-8") as f:
        md_text = f.read()

    md_text = strip_emoji(md_text)

    # Resolve metadata strictly from CLI args -- no markdown sniffing.
    document_title = title or _default_title_from_path(md_path)
    report_date = study_date or datetime.now().strftime("%B %Y")

    # Preprocessing pipeline: strip the boilerplate blocks out of the source
    # before parse_markdown sees them, so the parser stays dumb and renders
    # whatever's left as continuous body content.
    toc_titles, md_text = extract_and_strip_toc(md_text)
    md_text = strip_cover_block(md_text)
    if cover:
        md_text = strip_h1_if_matches_cover(md_text, document_title)

    # Body story
    content_story = parse_markdown(md_text, document_title)
    content_story = suppress_leading_rule(content_story)

    # Compose the full document story
    story = []

    if cover:
        story.extend(build_cover(
            document_title,
            subtitle,
            description,
            study_date or report_date,
            team,
        ))

    story.extend(build_toc(toc_titles))
    story.extend(content_story)

    # Build PDF
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=LEFT_MARGIN,
        rightMargin=RIGHT_MARGIN,
        topMargin=TOP_MARGIN + 0.15 * inch,
        bottomMargin=BOTTOM_MARGIN,
        title=document_title,
        author=team or "",
        # The canvas's starting font, so no page references a face that
        # font() didn't choose.
        initialFontName=font("Regular"),
    )

    # Bind document_title / report_date into the content footer callback
    # via partial so we don't reach for module globals.
    content_cb = partial(
        content_page_cb,
        document_title=document_title,
        report_date=report_date,
        footer_note=footer_note,
    )
    first_page_cb = cover_page_cb if cover else content_cb

    try:
        print(f"Building PDF with {len(story)} elements...", file=sys.stderr, flush=True)
        doc.build(story, onFirstPage=first_page_cb, onLaterPages=content_cb)
        print(f"PDF generated successfully: {output_path}")
        return output_path
    except Exception as e:
        print(f"ERROR during PDF build: {e}", file=sys.stderr)
        raise


# ============================================================
# 10. CLI
# ============================================================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate a PDF in USWDS styling (Public Sans, U.S. Web Design System color tokens) from markdown"
    )
    parser.add_argument("markdown_file", help="Path to markdown file")
    parser.add_argument("output_pdf", help="Path for output PDF")
    parser.add_argument("--cover", action="store_true", help="Render the dark blue cover page")
    parser.add_argument("--title", help="Cover title (also used for footer/PDF metadata)")
    parser.add_argument("--subtitle", help="Cover subtitle")
    parser.add_argument("--description", help="Small descriptive text on the cover")
    parser.add_argument("--date", help="Date shown on cover and in footer (e.g., 'April 2026')")
    parser.add_argument(
        "--team",
        help="Team name shown on the cover and used as the PDF author metadata (e.g., 'UX Research')",
    )
    parser.add_argument(
        "--footer-note",
        help=(
            "Optional note shown before the page number in the footer, rendered as "
            "'{note}  ·  Page {N}' (e.g., 'Confidential — Internal Use Only'). "
            "Without it the footer shows 'Page {N}' only."
        ),
    )
    parser.add_argument(
        "--font-dir",
        help=(
            "Directory containing the ten PublicSans-*.ttf files. Defaults to "
            "the fonts bundled with the skill (assets/fonts/). If any face "
            "can't be loaded, the PDF falls back to Helvetica."
        ),
    )

    args = parser.parse_args()

    if not os.path.exists(args.markdown_file):
        print(f"Error: File not found: {args.markdown_file}")
        sys.exit(1)

    build_document(
        args.markdown_file,
        args.output_pdf,
        cover=args.cover,
        title=args.title,
        subtitle=args.subtitle,
        description=args.description,
        study_date=args.date,
        team=args.team,
        font_dir=args.font_dir,
        footer_note=args.footer_note,
    )
