#!/usr/bin/env python3
"""Generate the Claude Code setup in .claude/ from the suite's own files.

Claude Code (the CLI and the VS Code extension) only discovers project agents in
.claude/agents/ and project skills in .claude/skills/<name>/SKILL.md, with its
own frontmatter format. The suite's sources stay where they are; this script
derives the Claude copies from them, so there is nothing to keep in step by hand:

  .claude/agents/research-*.md        the seven checkers, full copies, Claude
                                      frontmatter (read-only tools)
  .claude/skills/dr-morgan/SKILL.md   Dr. Morgan as a /dr-morgan skill, a full
                                      copy, so it runs in the main conversation
                                      and can launch the checkers itself
  .claude/skills/<skill>/SKILL.md     a pointer to each skill's real folder in
                                      skills/, so its references, scripts, and
                                      assets are never duplicated

Generated files: edit the sources, run ./build-claude.sh, commit both.
scripts/check.sh fails if .claude/ differs from a fresh build.
Stdlib only.
"""
import json
import os
import re
import shutil
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_AGENTS = os.path.join(REPO, ".claude", "agents")
OUT_SKILLS = os.path.join(REPO, ".claude", "skills")

STAMP = "<!-- Generated by build-claude.sh from {src}. Edit the source, not this file. -->\n\n"

CLAUDE_NOTE = """> **Running in Claude Code.** You were started with `/dr-morgan`, so you are the
> main conversation. The seven checkers are Claude Code subagents named
> `research-safety-checker`, `research-plan-reviewer`, `research-guide-checker`,
> `research-survey-checker`, `research-synthesis-checker`,
> `research-significance-checker`, and `research-readability-checker`
> (defined in `.claude/agents/`). Launch each with the Agent tool, giving it the
> checker packet as its entire prompt and naming source files by path rather
> than pasting them. Each launch starts with a fresh context, which is what
> THE EVALUATION LOOP below requires. Skills are available as `/` commands in
> `.claude/skills/`. Everything below applies unchanged.

"""


def split_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        sys.exit("no frontmatter")
    return m.group(1), m.group(2)


def field(front, key):
    """Read a scalar or folded (>, >-) YAML field without a YAML library."""
    lines = front.split("\n")
    for i, line in enumerate(lines):
        m = re.match(rf"^{key}:\s*(.*)$", line)
        if not m:
            continue
        val = m.group(1).strip()
        if val in (">", ">-", "|", "|-"):
            parts = []
            for nxt in lines[i + 1:]:
                if nxt.startswith(" ") or nxt == "":
                    parts.append(nxt.strip())
                else:
                    break
            return " ".join(p for p in parts if p)
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
            val = val[1:-1]
        return val
    return ""


def q(s):
    # JSON strings are valid YAML double-quoted scalars.
    return json.dumps(s, ensure_ascii=False)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def main():
    for d in (OUT_AGENTS, OUT_SKILLS):
        if os.path.isdir(d):
            shutil.rmtree(d)

    # Checkers
    agents_dir = os.path.join(REPO, "agents")
    for name in sorted(os.listdir(agents_dir)):
        if not (name.startswith("research-") and name.endswith(".agent.md")):
            continue
        src = f"agents/{name}"
        front, body = split_frontmatter(open(os.path.join(agents_dir, name), encoding="utf-8").read())
        slug = name[: -len(".agent.md")]
        out = (f"---\nname: {slug}\ndescription: {q(field(front, 'description'))}\n"
               f"tools: Read, Grep, Glob\n---\n" + STAMP.format(src=src) + body.lstrip("\n"))
        write(os.path.join(OUT_AGENTS, f"{slug}.md"), out)

    # Dr. Morgan as a user-invoked skill
    src = "agents/dr-morgan.agent.md"
    front, body = split_frontmatter(open(os.path.join(REPO, src), encoding="utf-8").read())
    desc = ("Start Dr. Morgan, the UX research mentor: coaching or drafting for "
            "research analysis, method selection, study plans, plan and guide "
            "critique, and competitive analysis, with every draft checked by the "
            "suite's seven checkers. " + field(front, "description"))
    out = (f"---\nname: dr-morgan\ndescription: {q(desc)}\n"
           f"disable-model-invocation: true\n---\n" + STAMP.format(src=src)
           + CLAUDE_NOTE + body.lstrip("\n"))
    write(os.path.join(OUT_SKILLS, "dr-morgan", "SKILL.md"), out)

    # Skills: pointers to the real folders
    skills_dir = os.path.join(REPO, "skills")
    for name in sorted(os.listdir(skills_dir)):
        skill_md = os.path.join(skills_dir, name, "SKILL.md")
        if not os.path.isfile(skill_md):
            continue
        front, _ = split_frontmatter(open(skill_md, encoding="utf-8").read())
        src = f"skills/{name}/SKILL.md"
        out = (f"---\nname: {name}\ndescription: {q(field(front, 'description'))}\n---\n"
               + STAMP.format(src=src)
               + f"This skill's files live in `skills/{name}/`, at the repo root. Read\n"
               f"`skills/{name}/SKILL.md` in full now and follow it. Resolve every\n"
               f"relative path it mentions (`references/`, `scripts/`, `assets/`) against\n"
               f"`skills/{name}/`, not this folder.\n")
        write(os.path.join(OUT_SKILLS, name, "SKILL.md"), out)

    # The Word document template is documented in skills/README.md
    readme = os.path.join(skills_dir, "README.md")
    front, _ = split_frontmatter(open(readme, encoding="utf-8").read())
    out = ("---\nname: research-document-template\n"
           f"description: {q(field(front, 'description'))}\n---\n"
           + STAMP.format(src="skills/README.md")
           + "This skill is documented in `skills/README.md`, with the config format in\n"
           "`skills/CONFIG-SCHEMA.md` and the renderer at\n"
           "`skills/research-document-template.py`. Read `skills/README.md` in full\n"
           "now and follow it; run the renderer from the repo root.\n")
    write(os.path.join(OUT_SKILLS, "research-document-template", "SKILL.md"), out)

    n_agents = len(os.listdir(OUT_AGENTS))
    n_skills = len(os.listdir(OUT_SKILLS))
    print(f"built .claude/: {n_agents} checker agents, {n_skills} skills")


if __name__ == "__main__":
    main()
